baseURL = "https://pianorganic.info/"
languageCode = "ru"
title = "Пианорганика"
theme = "introduction"
defaultContentLanguage = "ru"



[params]
    themeStyle                   = "light"                  # Choose "light" or "dark" or "auto"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showMenu                     = true                    # Show navigation menu
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "donfedorio@gmail.com"   # E-mail address for contact section
    customCSS                  = ["css/custom.css"] # Меняет цвет заголовка             # Include custom css files placed under assets/
    customJS                   = ["js/custom.js"]              # Include custom JavaScript files placed under assets/
    # plausible                  = true                    # Use Plausible analytics (requires an account at Plausible.io)

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = true                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = true                    # show all posts in an archive format
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "Europe/Moscow"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "ru-RUS"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = false
        facebook                 = false
        pinterest                = false

    # To enable giscus, the GitHub-discussions-based comment section,
    # input the repository for the discussions below. For more details, see
    # https://www.joelnitta.com/posts/2021-11-24_using-giscus/
    # and https://github.com/giscus/giscus
    [params.giscus]
        # repo = "github-user/github-repo" # Entering repo will enable giscus
        repo-id = "enter-repo-id"
        category = "Comments"
        category-id = "enter-category-id"
        mapping = "pathname"
        reactions-enabled = "1"
        emit-metadata = "0"
        theme = "light"
        lang = "en"

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://youtube.com/@pianorganic/"
        icon  = "fa-brands fa-youtube" # icon name without the 'fa-'
        icon_pack = "fab"
        target = "_blank"
    [[params.social]]
        url   = "https://www.instagram.com/pianorganic_trumpet?igsh=b3MzYnBwd3NsdDIx&utm_source=qr"
        icon  = "fa-brands fa-instagram" # icon name without the 'fa-'
        icon_pack = "fab"
        target = "_blank"
    [[params.social]]
        url   = "https://vk.com/pianorganic"
        icon  = "fa-brands fa-vk" # icon name without the 'fa-'
        icon_pack = "fab"
        target = "_blank"
    [[params.social]]
        url = "https://t.me/pianorganic" # For a direct email link, use "mailto:test@example.org". 
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"
        target = "_blank"


[languages]
    [languages.en]
        languageName     = "🇬🇧English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 1
        titleMain            = "Pianorganic"
        titleConjunction = "&"
        titleSub = "trumpet"
        [languages.en.params]
            description  = "Teaching playing piano and trumpet"   # Max 160 characters show in search results
            footerText   = "&copy;Pianorganic & Trumpet, 2025"                      # Text to override default footer text (markdown allowed)

    [languages.ru]
        languageName     = "🇷🇺Русский"
        languageCode     = "ru"
        contentDir       = "content/ru"
        weight           = 0
        titleMain            = "пианорганика"
        titleConjunction = "и"
        titleSub = "труба"
        [languages.ru.params]
            description  = "Обучение игре на фортепиано и трубе"
            footerText   = "&copy;Пианорганика и труба, 2025"